// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:ComeBearingPresence.Func.PresencePublisher.CheckPresenceForAll(Microsoft.Azure.WebJobs.TimerInfo,Microsoft.WindowsAzure.Storage.Table.CloudTable,Microsoft.Azure.WebJobs.IAsyncCollector{ComeBearingPresence.Func.Model.UserPresence})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:ComeBearingPresence.Func.CloudTableExtensions.Query``1(Microsoft.WindowsAzure.Storage.Table.CloudTable,System.String)~System.Threading.Tasks.Task{System.Collections.Generic.IEnumerable{``0}}")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:ComeBearingPresence.Func.CloudTableExtensions.Retrieve``1(Microsoft.WindowsAzure.Storage.Table.CloudTable,``0)~System.Threading.Tasks.Task{``0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:ComeBearingPresence.Func.PresencePublisher.AuthenticationResponseReceived(Microsoft.AspNetCore.Http.HttpRequest,Microsoft.Azure.WebJobs.IAsyncCollector{ComeBearingPresence.Func.Model.UserPresenceRequest})~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:ComeBearingPresence.Func.PresencePublisher.AuthStart(Microsoft.AspNetCore.Http.HttpRequest)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:ComeBearingPresence.Func.PresencePublisher.CheckPresenceForAllSync(Microsoft.AspNetCore.Http.HttpRequest,Microsoft.WindowsAzure.Storage.Table.CloudTable,Microsoft.WindowsAzure.Storage.Table.CloudTable,Microsoft.Azure.WebJobs.Binder)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:ComeBearingPresence.Func.PresencePublisher.GetLastPresence(Microsoft.AspNetCore.Http.HttpRequest,System.String,Microsoft.WindowsAzure.Storage.Table.CloudTable)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:ComeBearingPresence.Func.PresencePublisher.GetLivePresence(Microsoft.AspNetCore.Http.HttpRequest,System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA1801:Review unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ComeBearingPresence.Func.PresencePublisher.AuthStart(Microsoft.AspNetCore.Http.HttpRequest)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA1801:Review unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ComeBearingPresence.Func.PresencePublisher.CheckPresenceForAllSync(Microsoft.AspNetCore.Http.HttpRequest,Microsoft.WindowsAzure.Storage.Table.CloudTable,Microsoft.WindowsAzure.Storage.Table.CloudTable,Microsoft.Azure.WebJobs.Binder)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA1801:Review unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ComeBearingPresence.Func.PresencePublisher.GetLastPresence(Microsoft.AspNetCore.Http.HttpRequest,System.String,Microsoft.WindowsAzure.Storage.Table.CloudTable)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA1801:Review unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ComeBearingPresence.Func.PresencePublisher.GetLivePresence(Microsoft.AspNetCore.Http.HttpRequest,System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]